name: challengeOne
on: push
jobs:
  job1:
    name: ubuntuJob
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Print Date
        run: date "+%H:%M:%S   %d/%m/%y"
  job2:
    runs-on: windows-latest
    needs: ubuntuJob
    name: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Print Date
        run: "Get-Date"
    
  