name: challengeOne
on: push
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Print Date
        run: date "+%H:%M:%S   %d/%m/%y"
  windows:
    runs-on: windows-latest
    needs: [ubuntu]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Print Date
        run: "Get-Date"
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Print Date
        run: date

    
    
  